spring.application.name=user-service
server.port=9090
spring.config.import=optional:configserver
spring.cloud.config.enabled=false

#PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/event_management_system
spring.datasource.username=postgres
spring.datasource.password=purplepatch
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost


