spring.application.name=user-service
server.port=9090
spring.config.import=optional:configserver
spring.cloud.config.enabled=false

#PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/event_management_system
spring.datasource.username=postgres
spring.datasource.password=purplepatch
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# eureka configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost


# Keycloak (Authentication / Authorization)
# Keycloak base URL (matches docker-compose setup)
keycloak.auth-server-url=http://localhost:8080/
keycloak.realm=event-platform
keycloak.resource=user-service-client
keycloak.bearer-only=true
keycloak.ssl-required=external
keycloak.credentials.secret=DCvk5p6wXb7vZ7uQUjDkGi5hZmEquwPb


#OAuth2 Resource Server (JWT validation)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/event-platform

#Logging
logging.level.org.springframework.security=INFO
logging.level.org.keycloak=INFO
logging.level.com.user_service=DEBUG


