spring.application.name=config-server
server.port=8888

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


spring.cloud.config.server.git.uri=
spring.cloud.config.server.git.search-paths=/
spring.cloud.config.server.git.default-label=main
